In [1]:
import numpy as np
import scipy
import itertools
import pandas as pd

In [2]:
from fasano_franceschini_test import ff_test_2sample

In [3]:
impactor_aeis = np.load('true_impactor_aeis.npy')[:,:3]
sbdb_dm_neos = pd.read_csv('telescopic_decameter_neos.csv', sep=',')
# get the a, e, i, values and use the same H as for everything else:
sbdb_aeis = np.array(sbdb_dm_neos[['a', 'e', 'i']])

In [4]:
ff_test_2sample(s1=impactor_aeis, s2=sbdb_aeis)

2.8127510383779137

In [5]:
n, dim = impactor_aeis.shape
a = [(1, -1) for i in range(dim)]
permarr = np.array(list(itertools.product(*a)))


In [6]:
np.vstack([np.random.normal(0, 1, size=100), 
                       np.random.normal(0, 1, size=100), 
                       np.random.normal(0, 1, size=100), 
                       np.random.normal(0, 1, size=100)]).T

array([[-1.25548192e+00, -4.17531832e-01,  8.91956720e-02,
         9.88658080e-01],
       [-2.76444788e+00, -1.50288445e+00, -8.66251464e-01,
         1.76605299e+00],
       [ 7.79777941e-01,  5.45028816e-02,  5.36859311e-01,
        -2.67386102e-01],
       [-3.16733851e+00, -1.72453983e+00,  4.41206664e-01,
         6.85906315e-01],
       [ 3.19507217e-01,  1.84474490e+00, -9.51627042e-01,
         5.04205461e-01],
       [ 1.44073927e-01, -6.44489145e-02,  1.92071298e-01,
        -8.68911157e-01],
       [-1.08752920e+00,  5.97551998e-01, -1.92866059e-01,
        -4.41420358e-01],
       [ 1.39659972e+00, -1.61545981e+00, -2.01613259e+00,
         6.88023561e-01],
       [ 2.07692684e-01,  6.68296579e-02, -4.04635479e-01,
         2.14101095e-01],
       [ 1.26718711e+00,  2.74681412e+00,  9.67922446e-02,
         6.98601856e-01],
       [ 8.44173152e-01, -1.23696094e-01, -6.86152042e-01,
        -1.41292265e+00],
       [ 2.57293367e+00,  1.10533333e+00,  1.15480162e-03,
      

In [29]:
rand_norm1 = np.vstack([np.random.normal(1, 1, size=1000), 
                       np.random.normal(3, 1, size=1000), 
                       np.random.normal(4, 1, size=1000), 
                       np.random.normal(4, 1, size=1000)]).T
rand_norm2 = np.vstack([np.random.normal(2, 2, size=1000), 
                       np.random.normal(2, 2, size=1000), 
                       np.random.normal(3, 2, size=1000), 
                       np.random.normal(6, 2, size=1000)]).T
np.save('rand_norm1.npy', rand_norm1)
np.save('rand_norm2.npy', rand_norm2)

ff_test_2sample(s1=rand_norm1, s2=rand_norm2)

15.071098168348584

In [8]:
np.array(list(itertools.product(*[(1, -1) for d in range(dim)])))

array([[ 1,  1,  1],
       [ 1,  1, -1],
       [ 1, -1,  1],
       [ 1, -1, -1],
       [-1,  1,  1],
       [-1,  1, -1],
       [-1, -1,  1],
       [-1, -1, -1]])

In [9]:
impactor_aeis.shape, sbdb_aeis.shape

((14, 3), (295, 3))

In [10]:
len(impactor_aeis)

14

In [11]:
perm_impactor_aeis[:,0]

NameError: name 'perm_impactor_aeis' is not defined

In [75]:
def get_normalized_orth_probs(permarr, S, point):
    """
    get normalized orthant probabilities
    """
    f_orth_probs = np.zeros(len(permarr))

    perm_S = np.multiply(permarr[:, None], S)
    perm_point = np.multiply(permarr[:, None], point)
    f_orth_probs = np.sum(np.bitwise_and.reduce(perm_S > perm_point, axis=-1), axis=-1)
    # for i, perm in enumerate(permarr):
    #     # x1 < x2 is equivalent to -x1 > -x2: we want to evaluate whether the pont falls into a given orthant
    #     perm_S = np.multiply(perm, S)
    #     perm_point = np.multiply(perm, point)
    #     f_orth_probs[i] = np.sum(np.bitwise_and.reduce(perm_S > perm_point, axis=-1))

    return f_orth_probs/len(S)

In [84]:
orth_probs_s1 = get_normalized_orth_probs(permarr=permarr, S=impactor_aeis, point=aei)
orth_probs_s2 = get_normalized_orth_probs(permarr=permarr, S=sbdb_aeis, point=aei)

Dn1 = np.max(np.array([np.abs(f1-f2) for f1, f2 in zip(orth_probs_s1, orth_probs_s2)]))
Dn1

0.38305084745762713

In [76]:
(permarr[:, None] * impactor_aeis[0])

array([[[ 1.707077,  0.559619,  4.115442]],

       [[ 1.707077,  0.559619, -4.115442]],

       [[ 1.707077, -0.559619,  4.115442]],

       [[ 1.707077, -0.559619, -4.115442]],

       [[-1.707077,  0.559619,  4.115442]],

       [[-1.707077,  0.559619, -4.115442]],

       [[-1.707077, -0.559619,  4.115442]],

       [[-1.707077, -0.559619, -4.115442]]])

In [77]:
permarr_4 = np.array(list(itertools.product(*[(1, -1) for d in range(4)])))
(permarr_4[:, None] * rand_norm1).shape

(16, 1000, 4)

In [78]:
perm_S = (permarr[:, None] * impactor_aeis)
perm_point = (permarr[:, None] * aei)

np.sum(np.bitwise_and.reduce(perm_S > perm_point, axis=-1), axis=-1)

array([3, 6, 0, 0, 1, 1, 3, 0])

In [79]:
perm_S > perm_point

array([[[ True,  True, False],
        [ True,  True,  True],
        [False,  True,  True],
        [ True,  True, False],
        [ True,  True, False],
        [False, False,  True],
        [ True,  True, False],
        [ True,  True, False],
        [False, False,  True],
        [False,  True, False],
        [ True,  True, False],
        [ True,  True,  True],
        [ True,  True,  True],
        [False, False,  True]],

       [[ True,  True,  True],
        [ True,  True, False],
        [False,  True, False],
        [ True,  True,  True],
        [ True,  True,  True],
        [False, False, False],
        [ True,  True,  True],
        [ True,  True,  True],
        [False, False, False],
        [False,  True,  True],
        [ True,  True,  True],
        [ True,  True, False],
        [ True,  True, False],
        [False, False, False]],

       [[ True, False, False],
        [ True, False,  True],
        [False, False,  True],
        [ True, False, False],
    

In [80]:
A[:,None,:]*B[:,:,None]

NameError: name 'A' is not defined

In [81]:
np.multiply.outer(permarr, impactor_aeis).shape

(8, 3, 14, 3)

In [82]:
np.tensordot(permarr, impactor_aeis, axes=0).shape

(8, 3, 14, 3)

0.38305084745762713

In [ ]:
normalized_f_orth_probs = f_orth_probs/n

In [18]:
f_orth_probs = np.zeros(len(permarr))

In [15]:
aei = np.array([1.1, 0.25, 6.])

In [23]:
orth = np.multiply(permarr[2], impactor_aeis)


conditions = impactor_aeis > aei
f_orth_probs[2] = np.sum(np.bitwise_and.reduce(conditions, axis=-1))

In [22]:
impactor_aeis > aei

array([[ True,  True, False],
       [ True,  True,  True],
       [False,  True,  True],
       [ True,  True, False],
       [ True,  True, False],
       [False, False,  True],
       [ True,  True, False],
       [ True,  True, False],
       [False, False,  True],
       [False,  True, False],
       [ True,  True, False],
       [ True,  True,  True],
       [ True,  True,  True],
       [False, False,  True]])

In [107]:
[(impactor_as > a1) & (impactor_es > e1) & (impactor_is < i1)]

[array([ True, False, False,  True,  True, False,  True,  True, False,
        False,  True, False, False, False])]

In [53]:
np.multiply(iterarr[2], impactor_aeis), impactor_aeis

(array([[ 1.707077, -0.559619,  4.115442],
        [ 3.937435, -0.758731, 47.72114 ],
        [ 0.999096, -0.390349, 16.452354],
        [ 1.340342, -0.598135,  0.064387],
        [ 2.135537, -0.720735,  2.10109 ],
        [ 1.067342, -0.117548,  7.187758],
        [ 2.486342, -0.615878,  4.259817],
        [ 2.81715 , -0.657107,  0.118581],
        [ 0.823644, -0.232537, 11.632231],
        [ 0.624094, -0.625687,  3.94363 ],
        [ 2.097041, -0.534887,  5.909579],
        [ 1.942803, -0.5231  , 22.068825],
        [ 1.900956, -0.483911, 14.501607],
        [ 1.055591, -0.076817, 12.041149]]),
 array([[ 1.707077,  0.559619,  4.115442],
        [ 3.937435,  0.758731, 47.72114 ],
        [ 0.999096,  0.390349, 16.452354],
        [ 1.340342,  0.598135,  0.064387],
        [ 2.135537,  0.720735,  2.10109 ],
        [ 1.067342,  0.117548,  7.187758],
        [ 2.486342,  0.615878,  4.259817],
        [ 2.81715 ,  0.657107,  0.118581],
        [ 0.823644,  0.232537, 11.632231],
        [

In [81]:
conditions, impactor_as > a1

(array([[1., 1., 0.],
        [1., 1., 1.],
        [0., 1., 1.],
        [1., 1., 0.],
        [1., 1., 0.],
        [0., 0., 1.],
        [1., 1., 0.],
        [1., 1., 0.],
        [0., 0., 1.],
        [0., 1., 0.],
        [1., 1., 0.],
        [1., 1., 1.],
        [1., 1., 1.],
        [0., 0., 1.]]),
 array([ True,  True, False,  True,  True, False,  True,  True, False,
        False,  True,  True,  True, False]))

In [79]:
[(impactor_as > a1) & (impactor_es > e1) & (impactor_is > i1)]

[array([False,  True, False, False, False, False, False, False, False,
        False, False,  True,  True, False])]

In [41]:
a, e, i = 1, 3, 5
a1, e1, i1 = 1.1, 0.25, 6.

impactor_aeis = np.load('speed_radiant_difference/true_impactor_aeis.npy')[:,:3]
impactor_as, impactor_es, impactor_is = impactor_aeis.T

In [42]:
    fppp11 = len(impactor_aeis[(impactor_as > a1) & (impactor_es > e1) & (impactor_is > i1)])
    fppn11 = len(impactor_aeis[(impactor_as > a1) & (impactor_es > e1) & (impactor_is < i1)])
    fpnp11 = len(impactor_aeis[(impactor_as > a1) & (impactor_es < e1) & (impactor_is > i1)])
    fpnn11 = len(impactor_aeis[(impactor_as > a1) & (impactor_es < e1) & (impactor_is < i1)])
    
    fnpp11 = len(impactor_aeis[(impactor_as < a1) & (impactor_es > e1) & (impactor_is > i1)])
    fnpn11 = len(impactor_aeis[(impactor_as < a1) & (impactor_es > e1) & (impactor_is < i1)])
    fnnp11 = len(impactor_aeis[(impactor_as < a1) & (impactor_es < e1) & (impactor_is > i1)])
    fnnn11 = len(impactor_aeis[(impactor_as < a1) & (impactor_es < e1) & (impactor_is < i1)])

In [115]:
fppp11, fppn11, fpnp11, fpnn11, fnpp11, fnpn11, fnnp11, fnnn11

(3, 6, 0, 0, 1, 1, 3, 0)