In [1]:
import numpy as np
import scipy
import itertools
import pandas as pd

In [2]:
from fasano_franceschini_test import ff_test_2sample

In [3]:
# impactor_aeis = np.load('true_impactor_aeis.npy')[:,:3]
# sbdb_dm_neos = pd.read_csv('telescopic_decameter_neos.csv', sep=',')
# # get the a, e, i, values and use the same H as for everything else:
# sbdb_aeis = np.array(sbdb_dm_neos[['a', 'e', 'i']])

In [4]:
# ff_test_2sample(s1=impactor_aeis, s2=sbdb_aeis)

Test our K-S test implementation using multivariate normal data drawn from different distributions:

In [5]:
np.random.normal(1, 1, size=10000)[:, None]

array([[ 2.81646701],
       [ 1.59061752],
       [ 2.22172123],
       ...,
       [-0.50192694],
       [ 1.53507044],
       [-0.17979327]])

In [6]:
# s1t = np.random.normal(1, 1, size=10000)[:, None]
# s2t = np.random.normal(2, 1, size=10000)[:, None]
# ff_test_2sample(s1t, s2t)

In [7]:
s1 = np.vstack([np.random.normal(1, 1, size=1000), 
                       np.random.normal(3, 1, size=1000), 
                       np.random.normal(4, 1, size=1000), 
                       np.random.normal(4, 1, size=1000)]).T
s2 = np.vstack([np.random.normal(1, 1, size=1000), 
                       np.random.normal(3, 1, size=1000), 
                       np.random.normal(4, 1, size=1000), 
                       np.random.normal(4, 1, size=1000)]).T
# s1 = np.random.normal(1, 1, size=10)[:, None]
# s2 = np.random.normal(2, 1, size=10)[:, None]
np.save('rand_norm1.npy', s1)
np.save('rand_norm2.npy', s2)

In [8]:
Dn = ff_test_2sample(s1=s1, s2=s2, n_perms=100, threads='auto', seed=1234)
Dn

(1.1851160280748885, 0.8788850590215307)

In [10]:
Dn = ff_test_2sample(s1=s1, s2=s2, n_perms=100, threads='auto', seed=1234)
Dn

(1.1851160280748885, 0.8788850590215307)

In [11]:
rng = np.random.default_rng()

In [12]:
rng.uniform(0., 1.)

0.198532351271822

In [90]:
(rng.random(M) * 100).astype(int)

array([15, 30, 81, 94, 39,  0, 89, 61, 67, 73, 23, 28,  5,  9, 26, 49, 99,
       97, 42, 45, 21, 61, 81,  4, 54, 41, 94, 76, 63, 40, 52, 53, 60, 42,
        7, 92, 91, 50, 90, 24, 81, 55, 79, 87, 86, 67, 58, 46, 89, 76, 92,
       17, 89, 88, 75,  6, 51, 81, 78, 45, 60, 57, 52, 30, 54, 74, 99, 45,
       21, 36, 28, 22, 81, 71, 18, 96, 77, 56, 85, 48, 70, 25, 79, 23, 33,
       43, 57, 13, 97, 61, 67, 86, 42, 63, 81, 26, 64, 73, 90, 68, 23, 69,
       94, 38, 90, 29, 20, 44,  4, 97, 42, 18, 73, 60, 29, 84, 33, 73, 81,
       83, 78, 89,  1, 63, 22, 80, 35, 80, 87, 24, 35, 22, 39, 97, 43, 16,
       51, 51, 91, 93, 94, 53, 13, 48, 89, 63,  6, 44, 95, 25, 97, 56, 93,
       39, 21,  6, 62, 20, 42, 75, 93, 49, 20, 76,  7, 93, 53, 96, 96, 41,
       28, 87, 69, 48, 17, 26, 13, 56, 92,  8, 54, 17, 13, 58, 87,  6, 67,
        4, 40, 90, 74, 76, 22, 51, 10, 24, 22, 32, 24, 52, 58,  9, 82, 32,
       41, 89, 61, 84, 31, 86, 10, 68, 57, 97, 53, 54, 98, 33, 69, 56, 57,
       82,  9, 62, 76, 67

In [87]:
random.sample(range(1, 100), 3)

NameError: name 'random' is not defined

In [96]:
s = np.concatenate((s1, s2))
s

array([[ 1.28274367e+00,  2.92390988e+00,  9.82400464e-01,
         3.98201682e+00],
       [ 1.77986004e+00,  3.03270027e+00,  2.68546040e+00,
         2.80487480e+00],
       [-2.27548087e-02,  3.03872504e+00,  4.11453375e+00,
         5.11954321e+00],
       [ 2.10001113e+00,  2.47137238e+00,  3.22028076e+00,
         5.11244225e+00],
       [ 1.31191754e+00,  2.57323429e+00,  4.24724239e+00,
         3.65694022e+00],
       [ 5.76812538e-01,  2.97094292e+00,  2.38506249e+00,
         5.39226570e+00],
       [ 2.34190175e+00,  2.33732018e+00,  5.89150654e+00,
         5.52371501e+00],
       [ 1.61245031e+00,  2.47665398e+00,  3.64803861e+00,
         4.02171877e+00],
       [ 3.07528016e+00,  8.80122081e-01,  5.53107167e+00,
         4.74792251e+00],
       [ 6.18212147e-01,  3.31954961e+00,  2.15314458e+00,
         4.04248244e+00],
       [-2.42172003e+00, -8.15067164e-01,  2.82982474e+00,
         6.31512482e+00],
       [ 5.44098660e+00,  1.34448394e+00, -1.80019259e+00,
      

In [105]:
s

array([[ 1.28274367e+00,  2.92390988e+00,  9.82400464e-01,
         3.98201682e+00],
       [ 1.77986004e+00,  3.03270027e+00,  2.68546040e+00,
         2.80487480e+00],
       [-2.27548087e-02,  3.03872504e+00,  4.11453375e+00,
         5.11954321e+00],
       [ 2.10001113e+00,  2.47137238e+00,  3.22028076e+00,
         5.11244225e+00],
       [ 1.31191754e+00,  2.57323429e+00,  4.24724239e+00,
         3.65694022e+00],
       [ 5.76812538e-01,  2.97094292e+00,  2.38506249e+00,
         5.39226570e+00],
       [ 2.34190175e+00,  2.33732018e+00,  5.89150654e+00,
         5.52371501e+00],
       [ 1.61245031e+00,  2.47665398e+00,  3.64803861e+00,
         4.02171877e+00],
       [ 3.07528016e+00,  8.80122081e-01,  5.53107167e+00,
         4.74792251e+00],
       [ 6.18212147e-01,  3.31954961e+00,  2.15314458e+00,
         4.04248244e+00],
       [-2.42172003e+00, -8.15067164e-01,  2.82982474e+00,
         6.31512482e+00],
       [ 5.44098660e+00,  1.34448394e+00, -1.80019259e+00,
      

In [106]:
M = 1000
N = len(s1) + len(s2)
perm = rng.permutation(N)
s = np.concatenate((s1, s2))
s[perm[:len(s1)]], s[perm[-len(s2):]]

(array([[ 4.92544794e+00,  1.44077792e+00,  6.27437020e+00,
          7.34249505e+00],
        [ 5.76812538e-01,  2.97094292e+00,  2.38506249e+00,
          5.39226570e+00],
        [ 9.14952753e-03, -4.33919047e-01,  1.22469136e+00,
          9.48275934e+00],
        [-2.27548087e-02,  3.03872504e+00,  4.11453375e+00,
          5.11954321e+00],
        [ 3.62839120e+00,  5.64325619e+00,  9.64291745e+00,
          4.47029134e+00],
        [ 6.18212147e-01,  3.31954961e+00,  2.15314458e+00,
          4.04248244e+00],
        [ 2.93866053e-01,  1.92367971e+00,  4.41968912e+00,
          4.12945093e+00],
        [ 1.77986004e+00,  3.03270027e+00,  2.68546040e+00,
          2.80487480e+00],
        [ 2.10001113e+00,  2.47137238e+00,  3.22028076e+00,
          5.11244225e+00],
        [ 5.60712242e+00,  1.65381516e+00,  1.80243493e+00,
          5.98575819e+00]]),
 array([[-2.42172003, -0.81506716,  2.82982474,  6.31512482],
        [ 5.4409866 ,  1.34448394, -1.80019259,  9.47944977],
    

In [177]:
tests = np.array([[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14, 15]])
tests.shape

(4, 4)

In [234]:
arr.reshape(N, tests.size)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10,

In [147]:
rng.permuted(np.tile(s, N).reshape(N, s.size), axis=1).shape

(20, 80)

In [278]:
perm_indices[0]

NameError: name 'perm_indices' is not defined

In [276]:
perm_indices = rng.permuted(np.repeat([range(0, N)], tests.size, axis=0), axis=1)  # this can return duplicates i think
for indices in perm_indices:
    s1_perm, s2_perm = s[perm_indices[:n1]], s[perm[-n2:]]
    perm_indicators[i] = ff_test_2sample(s1_perm, s2_perm) >= Dn

array([[15, 16,  5,  0, 19, 13,  9, 11,  6,  2,  8,  4, 10, 14, 18, 12,
         3,  1, 17,  7],
       [ 8,  9,  0,  4,  6, 15,  3, 19, 13, 10, 18,  7,  5, 11,  1,  2,
        12, 14, 17, 16],
       [ 0,  8,  2, 18, 10, 16, 12,  7,  5, 11, 19, 17,  3, 13,  4,  1,
         9, 15, 14,  6],
       [ 9,  3, 13, 14,  1, 18,  4,  7,  8, 12, 15, 16, 11, 10, 19, 17,
         6,  2,  0,  5],
       [18,  3,  7,  4, 19,  0, 13, 17, 10,  1,  8,  5, 16, 11, 15, 12,
         9,  6, 14,  2],
       [13,  0,  5, 19, 16,  1,  3, 18, 12,  6, 17, 11,  2,  4, 10,  8,
         9, 15,  7, 14],
       [ 0, 17,  1,  3,  9,  6, 14, 11, 12,  8, 19, 10, 16, 18,  2,  4,
        13, 15,  7,  5],
       [ 4,  2,  6,  7,  8,  0, 15,  5, 14,  9, 10, 19, 18, 11, 12,  3,
        13,  1, 16, 17],
       [ 3,  0,  4, 17,  7, 13,  1, 12,  8, 14, 15, 11,  9, 10,  6,  2,
         5, 19, 18, 16],
       [11,  1, 16,  7,  4, 17, 12,  8,  3,  6, 14, 15,  0, 19, 10,  9,
        18,  5,  2, 13],
       [ 0,  7,  9, 14, 13, 19

In [300]:
import multiprocessing
multiprocessing.cpu_count()

16

In [ ]:
import multiprocessing

# initialize array for orbital parameters for all the events with the shape 
# (number of impact events, number of monte carlo samples per event, number of orbital parameters per monte carlo sample)
orb_param_array_all_events = np.zeros((len(impactor_state_vectors), n_monte_carlo_samples, len(orb_param_variables)))

# compute orbital parameters of Monte Carlo samples for each event in the decameter impactors table
for i, event in impactor_state_vectors.iterrows():
    
    # get the state vectors to input into the wmpl.Trajectory.Orbit file
    v = event['Speed']
    t = event['Time']
    a = event['Latitude Numerical']
    o = event['Longitude Numerical']
    e = event['Altitude(km)']
    azim = event['Radiant azimuth']
    # zenith distance, note that altitude is 90 minus the zenith distance! 
    zen = event['Zenith Distance']  # this is converted to alt in the get_monte_carlo_orbital_parameters function

    # create parameter list for multiprocessing for a number of Monte Carlo samples equal to n_monte_carlo_samples
    state_vector_par_list = np.repeat([[kde_model_dv, kde_model_log_drad, v, t, a, o, e, azim, zen]], n_monte_carlo_samples, axis=0)    
    # now compute the orbital parameters from the state vectors for each Monte Carlo sample, using multiprocessing:
    pool = multiprocessing.Pool(multiprocessing.cpu_count() - 1)  # avoids locking up the CPU by using every core
    # get the array of orbital parameters for all the monte carlo samples of this single event, using multiprocessing
    orb_param_array_single_event = np.asarray(list(tqdm(pool.imap(get_monte_carlo_orbital_parameters, state_vector_par_list))))
    # add the orb param array for this single event to the orbital parameter array for all events
    orb_param_array_all_events[i] = orb_param_array_single_event

In [363]:

pool.starmap(f)

<bound method Pool.imap of <multiprocessing.pool.Pool state=RUN pool_size=15>>

In [403]:
M = 100  # number of permutations
n1 = len(s1)
n2 = len(s2)
N = n1 + n2
s = np.concatenate((s1, s2))
Dn = ff_test_2sample(s1, s2)
rng = np.random.default_rng()
perm_indices = rng.permuted(np.repeat([range(0, N)], M, axis=0), axis=1)  # this can return duplicates i think
pool = multiprocessing.Pool(multiprocessing.cpu_count() - 1)
perm_ff_tests = np.array(list(pool.starmap(ff_test_2sample, zip(s[perm_indices[:,:n1]], s[perm_indices[:,-n2:]]))))

In [434]:
pval = np.sum(perm_ff_tests > Dn)/(1 + M) + np.random.uniform(0., 1.) * (1 + np.sum(perm_ff_tests == Dn))/(1 + M)
pval

0.6489542618931776

In [437]:
n1

1000

In [439]:
[(a, b, c) for a, b, c in zip(s[perm_indices[:,:n1]], s[perm_indices[:,-n2:]], np.repeat(0, M))]

[(array([[1.48550749, 1.94233597, 5.51895391, 2.16702549],
         [1.10003126, 2.19103774, 3.33133486, 4.92777825],
         [1.73771379, 2.67327986, 3.56035563, 2.88755283],
         ...,
         [0.84827213, 2.55154154, 6.72049707, 5.67794898],
         [0.62128066, 2.24683413, 5.26854372, 4.02548643],
         [0.53558066, 2.26779608, 4.03806564, 3.36877592]]),
  array([[0.45664867, 1.85701859, 5.53042818, 3.6584156 ],
         [0.56808506, 3.53401557, 4.24443631, 5.07301384],
         [2.8981548 , 3.25256168, 4.05381976, 4.86409558],
         ...,
         [1.94124153, 3.95650551, 4.85980826, 3.91195833],
         [1.23715047, 4.55555125, 4.00219471, 3.05384741],
         [1.32234289, 4.27442579, 3.78804452, 4.4691376 ]]),
  0),
 (array([[1.61913089, 2.94785816, 3.34644159, 3.05839493],
         [1.33703219, 3.74871027, 4.0542046 , 4.36303837],
         [0.82944897, 3.08770107, 3.95221601, 4.82041301],
         ...,
         [1.20185668, 2.80405861, 3.18150001, 3.39376626],
    

0.5815061610206332

0.006624816574399284

In [398]:
ff_test_2sample(s1, s2)

15.741918561598519

In [397]:
ff_test_2sample(s[perm_indices[:,:n1]][0], s[perm_indices[:,-n2:]][0])

1.1292143286373946

In [394]:
s[perm_indices[:,:n1]][0].shape, s[perm_indices[:,-n2:]][0].shape

((1000, 4), (1000, 4))

In [395]:
s1.shape, s2.shape

((1000, 4), (1000, 4))

In [383]:
[(a, b) for a, b in zip(s[perm_indices[:,:n1]], s[perm_indices[:,-n2:]])][0]

(array([[ 0.9424125 ,  2.67634378,  1.21468507,  7.06876447],
        [-0.80850621, -1.53705766,  5.00530014,  4.79339242],
        [ 3.33841139,  0.09992247,  3.55354443,  8.9547499 ],
        ...,
        [ 1.59615176,  1.7166914 ,  1.6700635 ,  3.19686597],
        [ 2.1607835 ,  3.20766063,  3.57635431,  3.00181471],
        [ 4.68669824,  2.35834276,  4.35076788,  3.13247431]]),
 array([[ 1.0026747 ,  4.00124614,  5.78464696,  5.17332246],
        [ 0.81004239,  0.24587987,  6.40704493,  9.09287216],
        [-0.58087823,  2.99838441,  5.13703558,  3.60259174],
        ...,
        [ 0.9835334 ,  2.98503281,  4.23872481,  4.08633506],
        [ 1.29019831,  4.09446492,  1.35353461,  6.07003324],
        [ 2.20150361,  3.88181102,  2.74234494,  3.12330532]]))

In [369]:
np.array(perm_ff_tests) >= 

(100,)

In [371]:
s[perm_indices[:,:n1]].shape, s[perm_indices[:,-n2:]].shape

((100, 1000, 4), (100, 1000, 4))

In [299]:
from tqdm import tqdm

M = 100  # number of permutations
n1 = len(s1)
n2 = len(s2)
N = n1 + n2
s = np.concatenate((s1, s2))
Dn = ff_test_2sample(s1, s2)
rng = np.random.default_rng()
perm_indices = rng.permuted(np.repeat([range(0, N)], M, axis=0), axis=1)  # this can return duplicates i think
for indices in tqdm(perm_indices):
    s1_perm, s2_perm = s[indices[:n1]], s[indices[-n2:]]
    # print(s1_perm, s2_perm)
    perm_indicators[i] = ff_test_2sample(s1_perm, s2_perm) >= Dn
pval = (1 + np.sum(perm_indicators))/(1 + M)
pval

 56%|███████████████████████████████████████████████████████████████████████████████████████████████▊                                                                           | 56/100 [01:13<00:57,  1.32s/it]


KeyboardInterrupt: 

In [39]:
np.concatenate((s1, s2))

array([[ 1.14959795,  4.27876472,  1.76335049,  3.3484565 ],
       [ 0.17237928,  4.67194232,  3.25489285,  4.73222137],
       [ 0.91518366,  2.78350608,  4.13631889,  4.93441133],
       [ 1.63283156,  3.41649788,  5.9232458 ,  3.23177237],
       [ 0.85304047,  2.94248692,  5.1274695 ,  4.91994131],
       [ 1.66493696,  2.75916759,  3.61332539,  2.82068767],
       [ 0.39179705,  0.66797294,  4.95133387,  5.04254071],
       [ 0.01068097,  3.31720073,  3.71735854,  3.32079939],
       [ 1.40605954,  2.87867043,  4.18571445,  3.73416981],
       [ 1.98580408,  3.29379363,  3.33637259,  4.03140528],
       [ 2.20292975,  5.25552613,  2.4554894 , 10.14526897],
       [ 3.7606164 ,  3.91489001,  3.51037988,  4.51145279],
       [ 4.33290474,  1.05164223,  5.29763083,  6.09581864],
       [ 0.35161205,  0.90688857,  6.20183772,  3.31488278],
       [ 1.38762103, -1.0908165 ,  0.74564053,  5.08641043],
       [ 0.54359402,  0.88348948,  0.14422902,  4.75706051],
       [-1.59175283,  2.

In [37]:
Z = [s1[i] if 0 <= i <= len(s1) - 1 else s2[i - len(s1)] for i in range(0, len(s1) + len(s2))]
Z

[array([1.14959795, 4.27876472, 1.76335049, 3.3484565 ]),
 array([0.17237928, 4.67194232, 3.25489285, 4.73222137]),
 array([0.91518366, 2.78350608, 4.13631889, 4.93441133]),
 array([1.63283156, 3.41649788, 5.9232458 , 3.23177237]),
 array([0.85304047, 2.94248692, 5.1274695 , 4.91994131]),
 array([1.66493696, 2.75916759, 3.61332539, 2.82068767]),
 array([0.39179705, 0.66797294, 4.95133387, 5.04254071]),
 array([0.01068097, 3.31720073, 3.71735854, 3.32079939]),
 array([1.40605954, 2.87867043, 4.18571445, 3.73416981]),
 array([1.98580408, 3.29379363, 3.33637259, 4.03140528]),
 array([ 2.20292975,  5.25552613,  2.4554894 , 10.14526897]),
 array([3.7606164 , 3.91489001, 3.51037988, 4.51145279]),
 array([4.33290474, 1.05164223, 5.29763083, 6.09581864]),
 array([0.35161205, 0.90688857, 6.20183772, 3.31488278]),
 array([ 1.38762103, -1.0908165 ,  0.74564053,  5.08641043]),
 array([0.54359402, 0.88348948, 0.14422902, 4.75706051]),
 array([-1.59175283,  2.20006061,  3.32130652,  4.16228977]),
 a

In [34]:
for i in range(0, len(s1) + len(s2)): print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [35]:
s2[19 - len(s1) + 1]

IndexError: index 10 is out of bounds for axis 0 with size 10

In [83]:
s1, permarr

(array([[ 1.12433698,  3.61793189,  4.97149858,  4.18309656],
        [ 0.21750925,  2.28951406,  4.35880004,  2.85059511],
        [ 0.51201694,  1.56815867,  1.56141988,  4.50927814],
        [ 2.18499876,  3.83145107,  5.08467691,  2.77601379],
        [-0.15310322,  3.05867635,  4.48253913,  4.79720863],
        [ 2.19802109,  2.03879718,  3.58010308,  5.20393172],
        [ 0.2810756 ,  3.69795649,  2.08229251,  4.23224847],
        [ 0.22376184,  2.40213639,  2.20812053,  3.82932113],
        [ 0.86229378,  4.35914421,  2.79397937,  4.20052104],
        [ 0.9107368 ,  2.90577816,  5.00589966,  3.98743878]]),
 array([[ 1,  1,  1,  1],
        [ 1,  1,  1, -1],
        [ 1,  1, -1,  1],
        [ 1,  1, -1, -1],
        [ 1, -1,  1,  1],
        [ 1, -1,  1, -1],
        [ 1, -1, -1,  1],
        [ 1, -1, -1, -1],
        [-1,  1,  1,  1],
        [-1,  1,  1, -1],
        [-1,  1, -1,  1],
        [-1,  1, -1, -1],
        [-1, -1,  1,  1],
        [-1, -1,  1, -1],
        [-1, -

In [111]:
permarr[:, None] * s1, permarr * s1[:, None]

(array([[[ 1.12433698,  3.61793189,  4.97149858,  4.18309656],
         [ 0.21750925,  2.28951406,  4.35880004,  2.85059511],
         [ 0.51201694,  1.56815867,  1.56141988,  4.50927814],
         [ 2.18499876,  3.83145107,  5.08467691,  2.77601379],
         [-0.15310322,  3.05867635,  4.48253913,  4.79720863],
         [ 2.19802109,  2.03879718,  3.58010308,  5.20393172],
         [ 0.2810756 ,  3.69795649,  2.08229251,  4.23224847],
         [ 0.22376184,  2.40213639,  2.20812053,  3.82932113],
         [ 0.86229378,  4.35914421,  2.79397937,  4.20052104],
         [ 0.9107368 ,  2.90577816,  5.00589966,  3.98743878]],
 
        [[ 1.12433698,  3.61793189,  4.97149858, -4.18309656],
         [ 0.21750925,  2.28951406,  4.35880004, -2.85059511],
         [ 0.51201694,  1.56815867,  1.56141988, -4.50927814],
         [ 2.18499876,  3.83145107,  5.08467691, -2.77601379],
         [-0.15310322,  3.05867635,  4.48253913, -4.79720863],
         [ 2.19802109,  2.03879718,  3.58010308, -5.

In [123]:
((permarr[:, None] * s1) > (permarr[:, None] * s1[0]))

array([[[False, False, False, False],
        [False, False, False, False],
        [False, False, False,  True],
        [ True,  True,  True, False],
        [False, False, False,  True],
        [ True, False, False,  True],
        [False,  True, False,  True],
        [False, False, False, False],
        [False,  True, False,  True],
        [False, False,  True, False]],

       [[False, False, False, False],
        [False, False, False,  True],
        [False, False, False, False],
        [ True,  True,  True,  True],
        [False, False, False, False],
        [ True, False, False, False],
        [False,  True, False, False],
        [False, False, False,  True],
        [False,  True, False, False],
        [False, False,  True,  True]],

       [[False, False, False, False],
        [False, False,  True, False],
        [False, False,  True,  True],
        [ True,  True, False, False],
        [False, False,  True,  True],
        [ True, False,  True,  True],
        

In [120]:
(permarr[:, None] * s1)[None, :, :, :].shape, (permarr * s1[:, None])[:, :, None, :].shape

((1, 16, 10, 4), (10, 16, 1, 4))

In [124]:
test1 = ((permarr[:, None] * s1)[None, :, :, :] > ((permarr * s1[:, None])[:, :, None, :]))
test1

array([[[[False, False, False, False],
         [False, False, False, False],
         [False, False, False,  True],
         ...,
         [False, False, False, False],
         [False,  True, False,  True],
         [False, False,  True, False]],

        [[False, False, False, False],
         [False, False, False,  True],
         [False, False, False, False],
         ...,
         [False, False, False,  True],
         [False,  True, False, False],
         [False, False,  True,  True]],

        [[False, False, False, False],
         [False, False,  True, False],
         [False, False,  True,  True],
         ...,
         [False, False,  True, False],
         [False,  True,  True,  True],
         [False, False, False, False]],

        ...,

        [[False, False, False, False],
         [ True,  True, False,  True],
         [ True,  True, False, False],
         ...,
         [ True,  True, False,  True],
         [ True, False, False, False],
         [ True,  True,  Tr

In [129]:
np.sum(np.bitwise_and.reduce(test1, axis=-1), axis=-1)/n1 == normed_orth_probs_s11

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  Tru

In [11]:
# lengths and dimensions of the two samples
n1, dim1 = s1.shape
n2, dim2 = s2.shape
# if they don't have same number of dimensions raise an error
if dim1 != dim2:
    raise TypeError('S1 and S2 do not have the same number of dimensions')
# create permutation array for all permutations of (-1, 1) over all D dimensions (length 2^D)
permarr = np.array(list(itertools.product(*[(1, -1) for d in range(dim1)])))
# orthant probabilities for all orthants and all samples from 1...n1 and 1...n2
normed_orth_probs_s11 = np.zeros((n1, 2 ** dim1))  # 2^D orthants for D dimensions
normed_orth_probs_s21 = np.zeros((n2, 2 ** dim1))
normed_orth_probs_s12 = np.zeros((n1, 2 ** dim1))
normed_orth_probs_s22 = np.zeros((n2, 2 ** dim1))
# Compute the probability of finding points in each of the 2^d volumes of d-dimensional space for the s1 samples
# by counting the fraction of points in each volume and dividing by the sample size

normed_orth_probs_s11 = np.sum(np.bitwise_and.reduce((permarr[:, None] * s1)[None, :, :, :] > 
                                                     (permarr * s1[:, None])[:, :, None, :], axis=-1), axis=-1)/n1
normed_orth_probs_s21 = np.sum(np.bitwise_and.reduce((permarr[:, None] * s2)[None, :, :, :] > 
                                                     (permarr * s1[:, None])[:, :, None, :], axis=-1), axis=-1)/n2

normed_orth_probs_s12 = np.sum(np.bitwise_and.reduce((permarr[:, None] * s1)[None, :, :, :] > 
                                                     (permarr * s2[:, None])[:, :, None, :], axis=-1), axis=-1)/n1
normed_orth_probs_s22 = np.sum(np.bitwise_and.reduce((permarr[:, None] * s2)[None, :, :, :] > 
                                                     (permarr * s2[:, None])[:, :, None, :], axis=-1), axis=-1)/n2

# for i1, point1 in enumerate(s1):
#     # gets the normalized orthant probabilities for s1, s2 over all permutations in permarr
#     # greater than or less than doesn't matter since the results are symmetric when considering all permutations
#     normed_orth_probs_s11[i1] = np.sum(np.bitwise_and.reduce((permarr[:, None] * s1) > (permarr[:, None] * point1), axis=-1), axis=-1)/n1
#     normed_orth_probs_s21[i1] = np.sum(np.bitwise_and.reduce((permarr[:, None] * s2) > (permarr[:, None] * point1), axis=-1), axis=-1)/n2
# # and the same for the s2 samples:
# for i2, point2 in enumerate(s2):
#     normed_orth_probs_s12[i2] = np.sum(np.bitwise_and.reduce((permarr[:, None] * s1) > (permarr[:, None] * point2), axis=-1),axis=-1)/n1
#     normed_orth_probs_s22[i2] = np.sum(np.bitwise_and.reduce((permarr[:, None] * s2) > (permarr[:, None] * point2), axis=-1), axis=-1)/n2

In [17]:
D1 = np.max(np.abs(normed_orth_probs_s11 - normed_orth_probs_s21))
D2 = np.max(np.abs(normed_orth_probs_s12 - normed_orth_probs_s22))
# Compute test statistic as the average of the two D1, D2 statistics scaled by the sample size:
Dn = np.sqrt((n1 * n2)/(n1 + n2)) * np.mean((D1, D2))

Dn

1.4534441853748634

In [16]:
s1_bc = (permarr[:, None] * s1)[None, :, :, :]  # broadcast array to broadcast
s1_pt = (permarr * s1[:, None])[:, :, None, :]  # point array to be broadcast over
s2_bc = (permarr[:, None] * s2)[None, :, :, :]
s2_pt = (permarr * s2[:, None])[:, :, None, :]
# Orthant probabilities for all orthants and all samples from 1...n1 and 1...n2
# Compute the probability of finding points in s1, s2 in each of the 2^d volumes of d-dimensional space for s1, s2 
# by counting the fraction of points in each volume and dividing by the sample size using numpy broadcasting for
# efficient vectorized operations
normed_orth_probs_s11 = np.sum(np.bitwise_and.reduce(s1_bc > s1_pt, axis=-1), axis=-1)/n1
normed_orth_probs_s21 = np.sum(np.bitwise_and.reduce(s2_bc > s1_pt, axis=-1), axis=-1)/n2
normed_orth_probs_s12 = np.sum(np.bitwise_and.reduce(s1_bc > s2_pt, axis=-1), axis=-1)/n1
normed_orth_probs_s22 = np.sum(np.bitwise_and.reduce(s2_bc > s2_pt, axis=-1), axis=-1)/n2

D1 = np.max(np.abs(normed_orth_probs_s11 - normed_orth_probs_s21))
D2 = np.max(np.abs(normed_orth_probs_s12 - normed_orth_probs_s22))
# Compute test statistic as the average of the two D1, D2 statistics scaled by the sample size:
Dn = np.sqrt((n1 * n2)/(n1 + n2)) * np.mean((D1, D2))

Dn

1.4534441853748634