In [1]:
import numpy as np
import scipy
import itertools
import pandas as pd

In [2]:
from fasano_franceschini_test import ff_test_2sample

In [3]:
# impactor_aeis = np.load('true_impactor_aeis.npy')[:,:3]
# sbdb_dm_neos = pd.read_csv('telescopic_decameter_neos.csv', sep=',')
# # get the a, e, i, values and use the same H as for everything else:
# sbdb_aeis = np.array(sbdb_dm_neos[['a', 'e', 'i']])

In [4]:
# ff_test_2sample(s1=impactor_aeis, s2=sbdb_aeis)

Test our K-S test implementation using multivariate normal data drawn from different distributions:

In [13]:
s1 = np.vstack([np.random.normal(1, 1, size=10000), 
                       np.random.normal(3, 1, size=10000), 
                       np.random.normal(4, 1, size=10000), 
                       np.random.normal(4, 1, size=10000)]).T
s2 = np.vstack([np.random.normal(2, 2, size=10), 
                       np.random.normal(2, 2, size=10), 
                       np.random.normal(3, 2, size=10), 
                       np.random.normal(6, 2, size=10)]).T
np.save('rand_norm1.npy', s1)
np.save('rand_norm2.npy', s2)

ff_test_2sample(s1=s1, s2=s2)

2.498847606525728

In [83]:
s1, permarr

(array([[ 1.12433698,  3.61793189,  4.97149858,  4.18309656],
        [ 0.21750925,  2.28951406,  4.35880004,  2.85059511],
        [ 0.51201694,  1.56815867,  1.56141988,  4.50927814],
        [ 2.18499876,  3.83145107,  5.08467691,  2.77601379],
        [-0.15310322,  3.05867635,  4.48253913,  4.79720863],
        [ 2.19802109,  2.03879718,  3.58010308,  5.20393172],
        [ 0.2810756 ,  3.69795649,  2.08229251,  4.23224847],
        [ 0.22376184,  2.40213639,  2.20812053,  3.82932113],
        [ 0.86229378,  4.35914421,  2.79397937,  4.20052104],
        [ 0.9107368 ,  2.90577816,  5.00589966,  3.98743878]]),
 array([[ 1,  1,  1,  1],
        [ 1,  1,  1, -1],
        [ 1,  1, -1,  1],
        [ 1,  1, -1, -1],
        [ 1, -1,  1,  1],
        [ 1, -1,  1, -1],
        [ 1, -1, -1,  1],
        [ 1, -1, -1, -1],
        [-1,  1,  1,  1],
        [-1,  1,  1, -1],
        [-1,  1, -1,  1],
        [-1,  1, -1, -1],
        [-1, -1,  1,  1],
        [-1, -1,  1, -1],
        [-1, -

In [111]:
permarr[:, None] * s1, permarr * s1[:, None]

(array([[[ 1.12433698,  3.61793189,  4.97149858,  4.18309656],
         [ 0.21750925,  2.28951406,  4.35880004,  2.85059511],
         [ 0.51201694,  1.56815867,  1.56141988,  4.50927814],
         [ 2.18499876,  3.83145107,  5.08467691,  2.77601379],
         [-0.15310322,  3.05867635,  4.48253913,  4.79720863],
         [ 2.19802109,  2.03879718,  3.58010308,  5.20393172],
         [ 0.2810756 ,  3.69795649,  2.08229251,  4.23224847],
         [ 0.22376184,  2.40213639,  2.20812053,  3.82932113],
         [ 0.86229378,  4.35914421,  2.79397937,  4.20052104],
         [ 0.9107368 ,  2.90577816,  5.00589966,  3.98743878]],
 
        [[ 1.12433698,  3.61793189,  4.97149858, -4.18309656],
         [ 0.21750925,  2.28951406,  4.35880004, -2.85059511],
         [ 0.51201694,  1.56815867,  1.56141988, -4.50927814],
         [ 2.18499876,  3.83145107,  5.08467691, -2.77601379],
         [-0.15310322,  3.05867635,  4.48253913, -4.79720863],
         [ 2.19802109,  2.03879718,  3.58010308, -5.

In [123]:
((permarr[:, None] * s1) > (permarr[:, None] * s1[0]))

array([[[False, False, False, False],
        [False, False, False, False],
        [False, False, False,  True],
        [ True,  True,  True, False],
        [False, False, False,  True],
        [ True, False, False,  True],
        [False,  True, False,  True],
        [False, False, False, False],
        [False,  True, False,  True],
        [False, False,  True, False]],

       [[False, False, False, False],
        [False, False, False,  True],
        [False, False, False, False],
        [ True,  True,  True,  True],
        [False, False, False, False],
        [ True, False, False, False],
        [False,  True, False, False],
        [False, False, False,  True],
        [False,  True, False, False],
        [False, False,  True,  True]],

       [[False, False, False, False],
        [False, False,  True, False],
        [False, False,  True,  True],
        [ True,  True, False, False],
        [False, False,  True,  True],
        [ True, False,  True,  True],
        

In [120]:
(permarr[:, None] * s1)[None, :, :, :].shape, (permarr * s1[:, None])[:, :, None, :].shape

((1, 16, 10, 4), (10, 16, 1, 4))

In [124]:
test1 = ((permarr[:, None] * s1)[None, :, :, :] > ((permarr * s1[:, None])[:, :, None, :]))
test1

array([[[[False, False, False, False],
         [False, False, False, False],
         [False, False, False,  True],
         ...,
         [False, False, False, False],
         [False,  True, False,  True],
         [False, False,  True, False]],

        [[False, False, False, False],
         [False, False, False,  True],
         [False, False, False, False],
         ...,
         [False, False, False,  True],
         [False,  True, False, False],
         [False, False,  True,  True]],

        [[False, False, False, False],
         [False, False,  True, False],
         [False, False,  True,  True],
         ...,
         [False, False,  True, False],
         [False,  True,  True,  True],
         [False, False, False, False]],

        ...,

        [[False, False, False, False],
         [ True,  True, False,  True],
         [ True,  True, False, False],
         ...,
         [ True,  True, False,  True],
         [ True, False, False, False],
         [ True,  True,  Tr

In [129]:
np.sum(np.bitwise_and.reduce(test1, axis=-1), axis=-1)/n1 == normed_orth_probs_s11

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  Tru

In [11]:
# lengths and dimensions of the two samples
n1, dim1 = s1.shape
n2, dim2 = s2.shape
# if they don't have same number of dimensions raise an error
if dim1 != dim2:
    raise TypeError('S1 and S2 do not have the same number of dimensions')
# create permutation array for all permutations of (-1, 1) over all D dimensions (length 2^D)
permarr = np.array(list(itertools.product(*[(1, -1) for d in range(dim1)])))
# orthant probabilities for all orthants and all samples from 1...n1 and 1...n2
normed_orth_probs_s11 = np.zeros((n1, 2 ** dim1))  # 2^D orthants for D dimensions
normed_orth_probs_s21 = np.zeros((n2, 2 ** dim1))
normed_orth_probs_s12 = np.zeros((n1, 2 ** dim1))
normed_orth_probs_s22 = np.zeros((n2, 2 ** dim1))
# Compute the probability of finding points in each of the 2^d volumes of d-dimensional space for the s1 samples
# by counting the fraction of points in each volume and dividing by the sample size

normed_orth_probs_s11 = np.sum(np.bitwise_and.reduce((permarr[:, None] * s1)[None, :, :, :] > 
                                                     (permarr * s1[:, None])[:, :, None, :], axis=-1), axis=-1)/n1
normed_orth_probs_s21 = np.sum(np.bitwise_and.reduce((permarr[:, None] * s2)[None, :, :, :] > 
                                                     (permarr * s1[:, None])[:, :, None, :], axis=-1), axis=-1)/n2

normed_orth_probs_s12 = np.sum(np.bitwise_and.reduce((permarr[:, None] * s1)[None, :, :, :] > 
                                                     (permarr * s2[:, None])[:, :, None, :], axis=-1), axis=-1)/n1
normed_orth_probs_s22 = np.sum(np.bitwise_and.reduce((permarr[:, None] * s2)[None, :, :, :] > 
                                                     (permarr * s2[:, None])[:, :, None, :], axis=-1), axis=-1)/n2

# for i1, point1 in enumerate(s1):
#     # gets the normalized orthant probabilities for s1, s2 over all permutations in permarr
#     # greater than or less than doesn't matter since the results are symmetric when considering all permutations
#     normed_orth_probs_s11[i1] = np.sum(np.bitwise_and.reduce((permarr[:, None] * s1) > (permarr[:, None] * point1), axis=-1), axis=-1)/n1
#     normed_orth_probs_s21[i1] = np.sum(np.bitwise_and.reduce((permarr[:, None] * s2) > (permarr[:, None] * point1), axis=-1), axis=-1)/n2
# # and the same for the s2 samples:
# for i2, point2 in enumerate(s2):
#     normed_orth_probs_s12[i2] = np.sum(np.bitwise_and.reduce((permarr[:, None] * s1) > (permarr[:, None] * point2), axis=-1),axis=-1)/n1
#     normed_orth_probs_s22[i2] = np.sum(np.bitwise_and.reduce((permarr[:, None] * s2) > (permarr[:, None] * point2), axis=-1), axis=-1)/n2

In [17]:
D1 = np.max(np.abs(normed_orth_probs_s11 - normed_orth_probs_s21))
D2 = np.max(np.abs(normed_orth_probs_s12 - normed_orth_probs_s22))
# Compute test statistic as the average of the two D1, D2 statistics scaled by the sample size:
Dn = np.sqrt((n1 * n2)/(n1 + n2)) * np.mean((D1, D2))

Dn

1.4534441853748634

In [16]:
s1_bc = (permarr[:, None] * s1)[None, :, :, :]  # broadcast array to broadcast
s1_pt = (permarr * s1[:, None])[:, :, None, :]  # point array to be broadcast over
s2_bc = (permarr[:, None] * s2)[None, :, :, :]
s2_pt = (permarr * s2[:, None])[:, :, None, :]
# Orthant probabilities for all orthants and all samples from 1...n1 and 1...n2
# Compute the probability of finding points in s1, s2 in each of the 2^d volumes of d-dimensional space for s1, s2 
# by counting the fraction of points in each volume and dividing by the sample size using numpy broadcasting for
# efficient vectorized operations
normed_orth_probs_s11 = np.sum(np.bitwise_and.reduce(s1_bc > s1_pt, axis=-1), axis=-1)/n1
normed_orth_probs_s21 = np.sum(np.bitwise_and.reduce(s2_bc > s1_pt, axis=-1), axis=-1)/n2
normed_orth_probs_s12 = np.sum(np.bitwise_and.reduce(s1_bc > s2_pt, axis=-1), axis=-1)/n1
normed_orth_probs_s22 = np.sum(np.bitwise_and.reduce(s2_bc > s2_pt, axis=-1), axis=-1)/n2

D1 = np.max(np.abs(normed_orth_probs_s11 - normed_orth_probs_s21))
D2 = np.max(np.abs(normed_orth_probs_s12 - normed_orth_probs_s22))
# Compute test statistic as the average of the two D1, D2 statistics scaled by the sample size:
Dn = np.sqrt((n1 * n2)/(n1 + n2)) * np.mean((D1, D2))

Dn

1.4534441853748634